- name: update apt
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"   
- name: Install apache2
  package:
    name: apache2
    state: present
  when: ansible_distribution == "Ubuntu"
- name: start apache2
  service:
    name: apache2
    state: started
  when: ansible_distribution == "Ubuntu"
- name: Install git
  package:
    name: git
    state: present
  when: ansible_distribution == "Ubuntu"
