- name: Selinux Permissive
  selinux:
    policy: targeted
    state: permissive
  when: ansible_distribution == "CentOS"
- name: Deploy ecom
  git:
    dest: /var/www/html
    repo: https://github.com/mrobel/ecomm.git
    force: yes
  when: ansible_distribution == "CentOS"
- name: Update new port
  template:
    src: httpd.j2
    dest: /etc/httpd/conf/httpd.conf 
  when: ansible_distribution == "CentOS"
  notify:
  - Restart httpd
